-- The Pomka Ecosystem Core Source Code
-- Copyright (C) 2026 Lev (Leo) Kondukov (aka DiceBarrel, Barrel, Vandi)
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

create table userbots(
    id bigint generated by default as identity primary key,
    username text unique not null,
    owner_id bigint references users(id) on delete cascade not null,
    relevancy bigint generated by default as identity unique,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp
);
create index on userbots(owner_id);
create trigger set_update_userbots before update on userbots
    for each row execute function update_modified_column();