create table user_tokens (
    id bigint generated by default as identity primary key ,
    user_id bigint references users(id) on delete cascade not null,
    amount bigint, -- may be null
    till timestamptz, -- may be null,
    used bigint not null default 0,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp,
    check(amount is null or amount >= used)
);

create trigger set_update_user_tokens before update on user_tokens
    for each row execute function update_modified_column();
create index idx_user_tokens_user on user_tokens(user_id);