create type user_role as enum(
    'pool',
    'deleted',
    'blocked',
    'user',
    'moderator',
    'admin',
    'owner'
);

create type notify_level as enum('no', 'default', 'all');

create table users (
    id bigint generated by default as identity primary key,
    name text,
    userhandle text unique,
    balance bigint not null default 0,
    role user_role default 'user' not null,
    notify_level notify_level default 'default' not null,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp,
    check (
        balance >= 0
        or role = 'pool'
    )
);

create trigger set_update_users before
update
    on users for each row execute function update_modified_column();

insert into
    users (id, name, role, notify_level)
VALUES
    (0, 'SYSTEM_REAL_POOL', 'pool', 'no');

create index idx_user_leaderboard on users (balance desc);