-- The Pomka Ecosystem Core Source Code
-- Copyright (C) 2026 Lev (Leo) Kondukov (aka DiceBarrel, Barrel, Vandi)
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

create type user_role as enum(
    'pool',
    'deleted',
    'blocked',
    'user',
    'moderator',
    'admin',
    'owner'
);

create type notify_level as enum('no', 'default', 'all');

create table users (
    id bigint generated by default as identity primary key,
    name text,
    userhandle text unique,
    balance bigint not null default 0,
    role user_role default 'user' not null,
    notify_level notify_level default 'default' not null,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp,
    check (
        balance >= 0
        or role = 'pool'
    )
);

create trigger set_update_users before
update
    on users for each row execute function update_modified_column();

insert into
    users (id, name, role, notify_level)
VALUES
    (0, 'SYSTEM_REAL_POOL', 'pool', 'no');

create index idx_user_leaderboard on users (balance desc);