-- The Pomka Ecosystem Core Source Code
-- Copyright (C) 2026 Lev (Leo) Kondukov (aka DiceBarrel, Barrel, Vandi)
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

create table transactions(
    id bigint generated by default as identity primary key,
    idempotency_key uuid unique,
    sender_id bigint references users(id) on delete no action not null,
    receiver_id bigint references users(id) on delete no action not null,
    amount bigint not null check(amount >= 0),
    executor bigint references executors(id) on delete no action not null,
    data jsonb, -- additional data to transaction
    type text not null,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp
);

create trigger set_update_transaction before update on transactions
    for each row execute function update_modified_column();
create index idx_transactions_receiver_id on transactions(receiver_id);
create index idx_transactions_sender_id on transactions(sender_id);
create index idx_transactions_executor on transactions(executor);
create index idx_transactions_created_at on transactions(created_at desc);
create index idx_transactions_sender_created on transactions(sender_id, created_at desc);
create index idx_transactions_receiver_created on transactions(receiver_id, created_at desc);
create index idx_transactions_executor_created on transactions(executor, created_at desc);
create index idx_transactions_type on transactions(type);