create table userbots(
    id bigint generated by default as identity primary key,
    username text unique not null,
    owner_id bigint references users(id) on delete cascade not null,
    relevancy bigint generated by default as identity unique,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp
);
create index on userbots(owner_id);
create trigger set_update_userbots before update on userbots
    for each row execute function update_modified_column();