create type user_role as enum(
    'pool',
    'blocked',
    'user',
    'moderator',
    'admin',
    'owner'
);
create type notify_level as enum(
    'no',
    'token-only',
    'important-only',
    'all'
);

create table users (
    id bigint generated by default as identity primary key,
    name text not null,
    balance bigint not null default 0,
    role user_role default 'user' not null ,
    notify_level notify_level default 'important-only' not null,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp,
    check (balance >= 0 or id = 0 ) -- allow for the pool to be negative
);
create trigger set_update_users before update on users
    for each row execute function  update_modified_column();

insert into users (id, name, role, notify_level) VALUES (0, 'SYSTEM_REAL_POOL', 'pool', 'no');

create index idx_user_leaderboard on users (balance desc);